packages:
  - apps/web
  - packages/*
  - mobile/*

ignoredBuiltDependencies:
  - '@prisma/client'
  - '@prisma/engines'
  - '@sentry/cli'
  - core-js
  - esbuild
  - prisma
  - sharp
  - unrs-resolver

nodeLinker: hoisted

# Reduce duplicate dependencies in monorepo
hoistPattern:
  - '*'
  - '!expo'
  - '!react'
  - '!react-dom'
  - '!react-native'

publicHoistPattern:
  - '*'