// Premium UNIQUE area copy for speedy-van.co.uk.
// Do NOT mirror copy from apps/web (speedyvan.uk) — Google duplicate-content risk.

export interface AreaItem {
  slug: string;
  name: string;
  region: string;
  postcodePrefix: string;
  fromPrice: string;
  intro: string;
  paragraphs: string[]; // 2-3 unique narrative paragraphs
  neighborhoods: string[]; // 6-10 neighbourhoods we serve
  popularRoutes: string[]; // 3-5 common move pairs
  lat: number;
  lng: number;
}

export const AREAS: AreaItem[] = [
  {
    slug: "glasgow",
    name: "Glasgow",
    region: "Central Belt",
    postcodePrefix: "G",
    fromPrice: "£45",
    intro: "Tenement-trained crews who actually know what a 'three up' means.",
    paragraphs: [
      "We move more homes in Glasgow than anywhere else in Scotland. From the West End sandstone flats to the new-build estates around Cambuslang and Robroyston, our crews know the closes, the loading bays, and the streets where double-parking will get you a ticket inside ten minutes.",
      "If you've ever tried to get a sofa up a Hyndland tenement, you'll know why having two trained people with proper straps is worth the fixed price. We don't drag, we don't scrape, and we don't promise things that physics won't allow.",
      "Same-day slots available across G1–G81 when booked before midday.",
    ],
    neighborhoods: [
      "West End",
      "Southside",
      "Merchant City",
      "East End",
      "Partick",
      "Dennistoun",
      "Shawlands",
      "Bearsden",
      "Newton Mearns",
      "Cambuslang",
    ],
    popularRoutes: [
      "Glasgow → Edinburgh",
      "Glasgow → Stirling",
      "West End → Newton Mearns",
      "Southside → Bearsden",
      "Glasgow → Aberdeen",
    ],
    lat: 55.8642,
    lng: -4.2518,
  },
  {
    slug: "edinburgh",
    name: "Edinburgh",
    region: "Central Belt",
    postcodePrefix: "EH",
    fromPrice: "£45",
    intro: "Cobbles, stairs, conservation rules — all in a normal Tuesday.",
    paragraphs: [
      "Edinburgh isn't an easy city to move in. The streets are narrow, half the buildings are listed, and parking permits expire faster than your patience. Our Edinburgh team treats every move like a logistics puzzle — because every move here is.",
      "We service the New Town, Old Town, Stockbridge and Marchmont (the tricky bits), as well as the easier suburbs of Corstorphine, Liberton and Currie. Conservation-area properties get extra protection on doorways and floors as standard.",
      "Festival season? Book early — we get full fast in August.",
    ],
    neighborhoods: [
      "New Town",
      "Old Town",
      "Stockbridge",
      "Marchmont",
      "Bruntsfield",
      "Leith",
      "Corstorphine",
      "Morningside",
      "Portobello",
      "South Queensferry",
    ],
    popularRoutes: [
      "Edinburgh → Glasgow",
      "Edinburgh → Dundee",
      "New Town → Stockbridge",
      "Leith → Portobello",
      "Edinburgh → London (long-distance)",
    ],
    lat: 55.9533,
    lng: -3.1883,
  },
  {
    slug: "aberdeen",
    name: "Aberdeen",
    region: "North East",
    postcodePrefix: "AB",
    fromPrice: "£55",
    intro: "Granite city moves with North Sea-grade reliability.",
    paragraphs: [
      "Aberdeen has its own rhythm. The energy sector keeps half the city in transition, and we move more rentals here in a month than some firms manage in a year. Our local crew know the patterns of Bridge of Don, Cults, Mannofield, and the city centre flats around Union Street.",
      "Long-distance moves to and from Aberdeen are a speciality — we run dedicated trucks south on a regular schedule, which keeps your price low without making you wait for a part-load.",
      "Inverurie, Westhill, Stonehaven and Banchory all sit inside our standard coverage.",
    ],
    neighborhoods: [
      "City Centre",
      "Bridge of Don",
      "Cults",
      "Mannofield",
      "Rosemount",
      "Hazlehead",
      "Garthdee",
      "Old Aberdeen",
      "Westhill",
      "Bucksburn",
    ],
    popularRoutes: [
      "Aberdeen → Edinburgh",
      "Aberdeen → Glasgow",
      "Aberdeen → Inverness",
      "Cults → City Centre",
      "Aberdeen → London",
    ],
    lat: 57.1497,
    lng: -2.0943,
  },
  {
    slug: "dundee",
    name: "Dundee",
    region: "East Coast",
    postcodePrefix: "DD",
    fromPrice: "£45",
    intro: "City of design, V&A — and our quietly busy East Coast hub.",
    paragraphs: [
      "Dundee has changed enormously in the last decade and we've moved a lot of the people who made it happen. Tech firms in Seabraes, students at Abertay and Dundee Uni, families in Broughty Ferry — every move treated the same: fixed quote, on time, done well.",
      "Half-day weekend slots are popular here and we recommend booking 5–7 days ahead during semester turnover.",
      "Onward routes to Perth, Arbroath and Montrose all run as standard same-day jobs.",
    ],
    neighborhoods: [
      "City Centre",
      "Broughty Ferry",
      "West End",
      "Lochee",
      "Stobswell",
      "Menzieshill",
      "Ninewells",
      "Riverside",
      "Whitfield",
      "Monifieth",
    ],
    popularRoutes: [
      "Dundee → Edinburgh",
      "Dundee → Aberdeen",
      "Dundee → Perth",
      "Broughty Ferry → City Centre",
      "Dundee → Glasgow",
    ],
    lat: 56.462,
    lng: -2.9707,
  },
  {
    slug: "inverness",
    name: "Inverness",
    region: "Highlands",
    postcodePrefix: "IV",
    fromPrice: "£65",
    intro: "Capital of the Highlands — and our most northerly fixed-price zone.",
    paragraphs: [
      "Inverness is one of the fastest-growing cities in the UK and the gateway to half the Highlands. We run regular routes north along the A9 and our Inverness slots cover everything from Crown to Smithton, plus the surrounding villages of Beauly, Nairn and Dingwall.",
      "Long-distance from Glasgow or Edinburgh to Inverness is one of our most-booked routes — we hold dedicated weekend slots specifically for it.",
      "Weather can affect Highlands moves Nov–Mar. We'll tell you honestly if we think a date is risky.",
    ],
    neighborhoods: [
      "City Centre",
      "Crown",
      "Smithton",
      "Culloden",
      "Westhill",
      "Hilton",
      "Raigmore",
      "Inshes",
      "Holm",
      "Ardersier",
    ],
    popularRoutes: [
      "Inverness → Aberdeen",
      "Inverness → Edinburgh",
      "Inverness → Glasgow",
      "Glasgow → Inverness",
      "Edinburgh → Inverness",
    ],
    lat: 57.4778,
    lng: -4.2247,
  },
  {
    slug: "stirling",
    name: "Stirling",
    region: "Central Belt",
    postcodePrefix: "FK",
    fromPrice: "£45",
    intro: "Geographic centre of Scotland — perfect midway hub.",
    paragraphs: [
      "Stirling sits at the crossroads of the country, which makes it both a busy local market and our favourite long-distance changeover point. We cover the city, the university campus at Bridge of Allan, and the surrounding villages of Dunblane, Doune and Killearn.",
      "Student moves spike in early September around the Uni of Stirling — we open extra slots specifically for that week.",
      "Onward to Falkirk, Larbert and Alloa with no surcharge.",
    ],
    neighborhoods: [
      "City Centre",
      "Bridge of Allan",
      "Causewayhead",
      "Cambusbarron",
      "Bannockburn",
      "Cornton",
      "Riverside",
      "St Ninians",
      "Raploch",
      "Dunblane",
    ],
    popularRoutes: [
      "Stirling → Glasgow",
      "Stirling → Edinburgh",
      "Bridge of Allan → Glasgow",
      "Stirling → Dundee",
      "Stirling → Perth",
    ],
    lat: 56.1165,
    lng: -3.9369,
  },
  {
    slug: "perth",
    name: "Perth",
    region: "Central Belt",
    postcodePrefix: "PH",
    fromPrice: "£45",
    intro: "Fair City moves with no fuel surcharges, ever.",
    paragraphs: [
      "Perth is small enough that the local moving market is well known to everyone — which is exactly why we keep our price card public. The drive north from Glasgow or south from Inverness is short enough that we never charge a long-distance premium for trips between Perth and the Central Belt.",
      "Common neighbourhoods include Bridgend, Letham, Scone, Bridge of Earn and Stanley.",
      "Same-day available when booked by 10am.",
    ],
    neighborhoods: [
      "City Centre",
      "Bridgend",
      "Letham",
      "Scone",
      "Bridge of Earn",
      "Tulloch",
      "Craigie",
      "Burghmuir",
      "Friarton",
      "Stanley",
    ],
    popularRoutes: [
      "Perth → Edinburgh",
      "Perth → Dundee",
      "Perth → Glasgow",
      "Perth → Inverness",
      "Scone → City Centre",
    ],
    lat: 56.3964,
    lng: -3.4371,
  },
  {
    slug: "falkirk",
    name: "Falkirk",
    region: "Central Belt",
    postcodePrefix: "FK1",
    fromPrice: "£45",
    intro: "Wheel and Kelpies country — quick onward routes both ways.",
    paragraphs: [
      "Falkirk is right in the middle of our Central Belt corridor and we cover it as a standard local zone. New-build estates around Polmont and Larbert are particularly busy with first-time buyer moves.",
      "Onward to Stirling, Glasgow, Edinburgh and Linlithgow with no premium.",
      "Same-day slots usually available — message us before midday.",
    ],
    neighborhoods: [
      "Town Centre",
      "Polmont",
      "Larbert",
      "Stenhousemuir",
      "Bonnybridge",
      "Camelon",
      "Grangemouth",
      "Bo'ness",
      "Bainsford",
      "Tamfourhill",
    ],
    popularRoutes: [
      "Falkirk → Edinburgh",
      "Falkirk → Glasgow",
      "Falkirk → Stirling",
      "Polmont → Edinburgh",
      "Falkirk → Linlithgow",
    ],
    lat: 56.0019,
    lng: -3.7839,
  },
  {
    slug: "kilmarnock",
    name: "Kilmarnock",
    region: "South West",
    postcodePrefix: "KA",
    fromPrice: "£55",
    intro: "Ayrshire's hub — and our short hop to the coast.",
    paragraphs: [
      "Kilmarnock sits at the heart of Ayrshire and we cover the town and its surrounding villages — Stewarton, Kilmaurs, Galston — as a single zone. Onward to Ayr, Troon and Prestwick is included in standard pricing inside KA postcodes.",
      "Long-distance moves to Glasgow or Edinburgh are common from Kilmarnock and run as fixed-price jobs with no per-mile surprises.",
      "Same-day available within Ayrshire when booked early.",
    ],
    neighborhoods: [
      "Town Centre",
      "New Farm Loch",
      "Bellfield",
      "Crookedholm",
      "Hurlford",
      "Riccarton",
      "Stewarton",
      "Kilmaurs",
      "Galston",
      "Onthank",
    ],
    popularRoutes: [
      "Kilmarnock → Glasgow",
      "Kilmarnock → Ayr",
      "Kilmarnock → Edinburgh",
      "Stewarton → Glasgow",
      "Kilmarnock → Prestwick",
    ],
    lat: 55.6111,
    lng: -4.4956,
  },
  {
    slug: "ayr",
    name: "Ayr",
    region: "South West",
    postcodePrefix: "KA7",
    fromPrice: "£55",
    intro: "Coastal moves with no surcharge for the sea air.",
    paragraphs: [
      "Ayr is one of our favourite seaside zones — we cover the town centre, Alloway, Doonfoot, and onward to Prestwick, Troon and Maybole. Beach-front properties are no problem; we know the access codes for most of the harbour blocks.",
      "Routes to Glasgow city centre and the airport at Prestwick are common, fast, and fixed-price.",
      "Open all summer with extended weekend slots.",
    ],
    neighborhoods: [
      "Town Centre",
      "Alloway",
      "Doonfoot",
      "Prestwick",
      "Troon",
      "Heathfield",
      "Whitletts",
      "Castlehill",
      "Mossblown",
      "Maybole",
    ],
    popularRoutes: [
      "Ayr → Glasgow",
      "Ayr → Kilmarnock",
      "Ayr → Edinburgh",
      "Prestwick → Glasgow Airport",
      "Ayr → Troon",
    ],
    lat: 55.4609,
    lng: -4.6292,
  },
  {
    slug: "dumfries",
    name: "Dumfries",
    region: "South West",
    postcodePrefix: "DG",
    fromPrice: "£75",
    intro: "Scotland's quiet south — covered with the same fixed-price promise.",
    paragraphs: [
      "Dumfries is geographically the furthest south we run as a standard zone. We've moved families from Castle Douglas, Lockerbie and Annan to all corners of the Central Belt — and back the other way for retirees seeking a slower pace.",
      "Cross-border routes into Carlisle and Cumbria are available on request.",
      "Book 3–5 days ahead for the best slot availability.",
    ],
    neighborhoods: [
      "Town Centre",
      "Maxwelltown",
      "Heathhall",
      "Locharbriggs",
      "Lochside",
      "Georgetown",
      "Castle Douglas",
      "Annan",
      "Lockerbie",
      "Dalbeattie",
    ],
    popularRoutes: [
      "Dumfries → Glasgow",
      "Dumfries → Edinburgh",
      "Dumfries → Carlisle",
      "Annan → Glasgow",
      "Dumfries → Ayr",
    ],
    lat: 55.0709,
    lng: -3.6033,
  },
  {
    slug: "fort-william",
    name: "Fort William",
    region: "Highlands",
    postcodePrefix: "PH33",
    fromPrice: "£85",
    intro: "Outdoor capital of the UK — and our western Highlands base.",
    paragraphs: [
      "Fort William and the surrounding Lochaber area are remote, but they're not unreachable. We run scheduled routes from the Central Belt that allow us to keep the price fixed and predictable, even at the foot of Ben Nevis.",
      "Coverage extends to Glencoe, Mallaig, Spean Bridge and along the Road to the Isles.",
      "Winter weather can affect availability Nov–Mar — we'll tell you up front if we have concerns about a date.",
    ],
    neighborhoods: [
      "Town Centre",
      "Caol",
      "Inverlochy",
      "Banavie",
      "Corpach",
      "Spean Bridge",
      "Glencoe",
      "Mallaig",
      "Onich",
      "Kinlochleven",
    ],
    popularRoutes: [
      "Fort William → Glasgow",
      "Fort William → Edinburgh",
      "Fort William → Inverness",
      "Glasgow → Fort William",
      "Edinburgh → Fort William",
    ],
    lat: 56.8198,
    lng: -5.1052,
  },
  {
    slug: "oban",
    name: "Oban",
    region: "Highlands",
    postcodePrefix: "PA34",
    fromPrice: "£85",
    intro: "Gateway to the Isles — moves to and from the West Coast harbour.",
    paragraphs: [
      "Oban is a working harbour town, the jumping-off point for Mull, Iona and the Inner Hebrides. We move people to and from Oban regularly, often connecting to ferry crossings — co-ordinating our drop-off with sailing times so nothing waits on the pier longer than it needs to.",
      "Onward to the islands available on quoted basis (we work with the ferry operator's cargo team).",
      "Routes from the Central Belt run on fixed weekend slots — book early.",
    ],
    neighborhoods: [
      "Town Centre",
      "Soroba",
      "Glencruitten",
      "Pulpit Hill",
      "North Pier",
      "Battery Hill",
      "Connel",
      "Benderloch",
      "Taynuilt",
      "Kilmore",
    ],
    popularRoutes: [
      "Oban → Glasgow",
      "Oban → Edinburgh",
      "Oban → Fort William",
      "Glasgow → Oban",
      "Oban → Mull (ferry)",
    ],
    lat: 56.4154,
    lng: -5.4719,
  },
];

export function getArea(slug: string): AreaItem | undefined {
  return AREAS.find((a) => a.slug === slug);
}

export const REGIONS = ["Central Belt", "East Coast", "North East", "Highlands", "South West"] as const;
