import { z } from 'zod';
import { BaseTool, ToolContext, ToolResult } from './base/ToolExecutor';
import { orderTools } from './orderTools';
import { driverTools } from './driverTools';
import { financeTools } from './financeTools';
import { analyticsTools } from './analyticsTools';

/**
 * Action plan step
 */
interface ActionStep {
  id: string;
  tool: string;
  input: Record<string, any>;
  description: string;
  requiresConfirmation?: boolean;
  dependsOn?: string[]; // IDs of steps that must complete first
}

/**
 * Action plan generated by AOE
 */
interface ActionPlan {
  id: string;
  goal: string;
  steps: ActionStep[];
  estimatedDuration: number; // seconds
  riskLevel: 'low' | 'medium' | 'high';
  createdAt: Date;
}

/**
 * Execution result for a step
 */
interface StepResult {
  stepId: string;
  success: boolean;
  data?: any;
  error?: string;
  duration: number;
}

/**
 * Autonomous Operations Engine (AOE)
 * Converts natural language requests into executable action plans
 */
export class AutonomousOpsEngine {
  private tools: Map<string, BaseTool<any, any>>;

  constructor() {
    // Register all available tools
    this.tools = new Map();
    
    [...orderTools, ...driverTools, ...financeTools, ...analyticsTools].forEach(tool => {
      this.tools.set(tool.name, tool);
    });
  }

  /**
   * Parse natural language request and generate action plan
   */
  async generateActionPlan(request: string, context: ToolContext): Promise<ActionPlan> {
    const requestLower = request.toLowerCase();
    const steps: ActionStep[] = [];
    let riskLevel: 'low' | 'medium' | 'high' = 'low';

    // Pattern matching for common requests
    // ORDER MANAGEMENT
    if (requestLower.includes('unassigned order') || requestLower.includes('orders without driver')) {
      steps.push({
        id: 'step_1',
        tool: 'get_unassigned_orders',
        input: { limit: 50 },
        description: 'Fetch all unassigned orders',
      });
    }

    if (requestLower.includes('assign') && requestLower.includes('driver')) {
      // Extract order and driver IDs if present
      const orderMatch = requestLower.match(/order[:\s]+([a-z0-9-]+)/i);
      const driverMatch = requestLower.match(/driver[:\s]+([a-z0-9-]+)/i);

      if (orderMatch && driverMatch) {
        steps.push({
          id: 'step_assign',
          tool: 'assign_driver_to_order',
          input: {
            orderId: orderMatch[1],
            driverId: driverMatch[1],
            reason: 'Admin assigned via AI Assistant',
          },
          description: `Assign driver ${driverMatch[1]} to order ${orderMatch[1]}`,
          requiresConfirmation: true,
        });
        riskLevel = 'medium';
      } else {
        // Auto-assign workflow
        steps.push({
          id: 'step_1',
          tool: 'get_unassigned_orders',
          input: { limit: 10, sortBy: 'scheduledAt' },
          description: 'Get next unassigned orders',
        });
      }
    }

    if (requestLower.includes('cancel order')) {
      const orderMatch = requestLower.match(/order[:\s]+([a-z0-9-]+)/i);
      if (orderMatch) {
        steps.push({
          id: 'step_cancel',
          tool: 'cancel_order',
          input: {
            orderId: orderMatch[1],
            reason: requestLower.includes('reason') 
              ? requestLower.split('reason')[1].trim()
              : 'Cancelled by admin',
          },
          description: `Cancel order ${orderMatch[1]}`,
          requiresConfirmation: true,
        });
        riskLevel = 'high';
      }
    }

    // DRIVER MANAGEMENT
    if (requestLower.includes('available driver') || requestLower.includes('free driver')) {
      steps.push({
        id: 'step_drivers',
        tool: 'get_available_drivers',
        input: {},
        description: 'Get all available drivers',
      });
    }

    if (requestLower.includes('driver status') && requestLower.includes('change')) {
      const driverMatch = requestLower.match(/driver[:\s]+([a-z0-9-]+)/i);
      const statusMatch = requestLower.match(/(active|inactive|suspended)/i);
      
      if (driverMatch && statusMatch) {
        steps.push({
          id: 'step_status',
          tool: 'update_driver_status',
          input: {
            driverId: driverMatch[1],
            status: statusMatch[1].toLowerCase(),
            reason: 'Status changed via AI Assistant',
          },
          description: `Update driver ${driverMatch[1]} status to ${statusMatch[1]}`,
          requiresConfirmation: true,
        });
        riskLevel = 'medium';
      }
    }

    if (requestLower.includes('driver performance') || requestLower.includes('top driver')) {
      steps.push({
        id: 'step_perf',
        tool: 'get_driver_performance_analytics',
        input: {
          period: requestLower.includes('week') ? 'week' : 'month',
          topN: 10,
        },
        description: 'Analyze driver performance',
      });
    }

    // FINANCE
    if (requestLower.includes('revenue') || requestLower.includes('income')) {
      steps.push({
        id: 'step_revenue',
        tool: 'generate_revenue_report',
        input: {
          startDate: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000).toISOString(),
          endDate: new Date().toISOString(),
          groupBy: 'day',
        },
        description: 'Generate revenue report',
      });
    }

    if (requestLower.includes('refund')) {
      const orderMatch = requestLower.match(/order[:\s]+([a-z0-9-]+)/i);
      const amountMatch = requestLower.match(/(\d+(?:\.\d+)?)/);
      
      if (orderMatch && amountMatch) {
        steps.push({
          id: 'step_refund',
          tool: 'process_refund',
          input: {
            orderId: orderMatch[1],
            amount: parseFloat(amountMatch[1]),
            reason: 'Refund processed via AI Assistant',
          },
          description: `Process refund for order ${orderMatch[1]}`,
          requiresConfirmation: true,
        });
        riskLevel = 'high';
      }
    }

    if (requestLower.includes('financial summary') || requestLower.includes('finance overview')) {
      steps.push({
        id: 'step_summary',
        tool: 'get_financial_summary',
        input: {
          period: requestLower.includes('today') ? 'today' 
            : requestLower.includes('week') ? 'week'
            : requestLower.includes('year') ? 'year'
            : 'month',
        },
        description: 'Get financial summary',
      });
    }

    if (requestLower.includes('outstanding') || requestLower.includes('unpaid')) {
      steps.push({
        id: 'step_outstanding',
        tool: 'get_outstanding_payments',
        input: { limit: 50 },
        description: 'Get outstanding payments',
      });
    }

    // ANALYTICS
    if (requestLower.includes('kpi') || requestLower.includes('metrics')) {
      steps.push({
        id: 'step_kpi',
        tool: 'get_kpis',
        input: {
          period: requestLower.includes('today') ? 'today' 
            : requestLower.includes('week') ? 'week'
            : 'month',
          compareWithPrevious: true,
        },
        description: 'Get key performance indicators',
      });
    }

    if (requestLower.includes('trend') || requestLower.includes('pattern')) {
      steps.push({
        id: 'step_trend',
        tool: 'get_order_trends',
        input: {
          days: requestLower.includes('week') ? 7 : 30,
          groupBy: 'day',
        },
        description: 'Analyze order trends',
      });
    }

    if (requestLower.includes('customer behavior') || requestLower.includes('customer analytics')) {
      steps.push({
        id: 'step_customer',
        tool: 'get_customer_behavior_analytics',
        input: {
          segment: requestLower.includes('new') ? 'new'
            : requestLower.includes('vip') ? 'vip'
            : 'all',
        },
        description: 'Analyze customer behavior',
      });
    }

    if (requestLower.includes('efficiency') || requestLower.includes('bottleneck')) {
      steps.push({
        id: 'step_efficiency',
        tool: 'get_operational_efficiency',
        input: { period: 'month' },
        description: 'Analyze operational efficiency',
      });
    }

    // COMBINED WORKFLOWS
    if (requestLower.includes('auto assign') || requestLower.includes('smart assign')) {
      steps.push(
        {
          id: 'step_1',
          tool: 'get_unassigned_orders',
          input: { limit: 10, sortBy: 'scheduledAt' },
          description: 'Get unassigned orders',
        },
        {
          id: 'step_2',
          tool: 'get_available_drivers',
          input: {},
          description: 'Get available drivers',
          dependsOn: ['step_1'],
        }
      );
      riskLevel = 'medium';
    }

    if (requestLower.includes('daily report') || requestLower.includes('daily summary')) {
      steps.push(
        {
          id: 'step_1',
          tool: 'get_kpis',
          input: { period: 'today', compareWithPrevious: true },
          description: 'Get today\'s KPIs',
        },
        {
          id: 'step_2',
          tool: 'get_financial_summary',
          input: { period: 'today' },
          description: 'Get today\'s financials',
        },
        {
          id: 'step_3',
          tool: 'get_available_drivers',
          input: {},
          description: 'Get current driver availability',
        },
        {
          id: 'step_4',
          tool: 'get_unassigned_orders',
          input: { limit: 20 },
          description: 'Get pending orders',
        }
      );
    }

    // If no steps matched, return error plan
    if (steps.length === 0) {
      return {
        id: `plan_${Date.now()}`,
        goal: request,
        steps: [],
        estimatedDuration: 0,
        riskLevel: 'low',
        createdAt: new Date(),
      };
    }

    return {
      id: `plan_${Date.now()}`,
      goal: request,
      steps,
      estimatedDuration: steps.length * 2, // 2 seconds per step estimate
      riskLevel,
      createdAt: new Date(),
    };
  }

  /**
   * Execute an action plan
   */
  async executeActionPlan(
    plan: ActionPlan,
    context: ToolContext,
    onProgress?: (step: ActionStep, result: StepResult) => void
  ): Promise<{
    success: boolean;
    results: StepResult[];
    summary: string;
  }> {
    const results: StepResult[] = [];
    const completedSteps = new Set<string>();

    for (const step of plan.steps) {
      // Check dependencies
      if (step.dependsOn) {
        const dependenciesMet = step.dependsOn.every(dep => completedSteps.has(dep));
        if (!dependenciesMet) {
          results.push({
            stepId: step.id,
            success: false,
            error: 'Dependencies not met',
            duration: 0,
          });
          continue;
        }
      }

      const tool = this.tools.get(step.tool);
      if (!tool) {
        results.push({
          stepId: step.id,
          success: false,
          error: `Tool ${step.tool} not found`,
          duration: 0,
        });
        continue;
      }

      const startTime = Date.now();
      let result: ToolResult<any>;

      try {
        if (step.requiresConfirmation) {
          result = await tool.executeWithConfirmation(
            step.input, 
            context, 
            'auto_confirmed',
            'Auto-confirmed by AOE'
          );
        } else {
          result = await tool.execute(step.input, context);
        }

        const stepResult: StepResult = {
          stepId: step.id,
          success: result.success,
          data: result.data,
          error: result.error,
          duration: Date.now() - startTime,
        };

        results.push(stepResult);
        completedSteps.add(step.id);

        if (onProgress) {
          onProgress(step, stepResult);
        }

        // Stop execution if step failed
        if (!result.success) {
          break;
        }
      } catch (error) {
        results.push({
          stepId: step.id,
          success: false,
          error: error instanceof Error ? error.message : 'Unknown error',
          duration: Date.now() - startTime,
        });
        break;
      }
    }

    const successCount = results.filter(r => r.success).length;
    const totalSteps = plan.steps.length;

    return {
      success: successCount === totalSteps,
      results,
      summary: `Completed ${successCount}/${totalSteps} steps for: ${plan.goal}`,
    };
  }

  /**
   * Get tool by name
   */
  getTool(name: string): BaseTool<any, any> | undefined {
    return this.tools.get(name);
  }

  /**
   * List all available tools
   */
  listTools(): Array<{ name: string; description: string; riskLevel: string }> {
    return Array.from(this.tools.values()).map(tool => ({
      name: tool.name,
      description: tool.description,
      riskLevel: tool.riskLevel,
    }));
  }
}

// Singleton instance
export const autonomousOpsEngine = new AutonomousOpsEngine();
